# Generated by Django 5.0.6 on 2024-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blindtest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicfile",
            name="play_position",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="musicfile",
            name="room_number",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
