# Generated by Django 5.0.6 on 2024-06-16 15:50

import blindtest.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blindtest", "0004_alter_musicfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicfile",
            name="file",
            field=models.FileField(upload_to=blindtest.models.upload_to),
        ),
    ]
